version: '3.7'

x-common:
  &common
  image: node:14.14.0-alpine
  env_file: .env
  networks:
    - advanced-testing-network

x-frontend-volumes:
  &frontend-volumes
  volumes:
    # frontend sources
    - ./:/frontend:delegated

services:

  balancer:
    <<: *common
    image: advanced-testing-openresty
    container_name: balancer
    environment:
      DNS_NAME: $BACKEND_HOSTNAME
    volumes:
      # openresty
      - ./openresty/conf:/etc/openresty
      - ./.data/openresty/ssl:/etc/openresty/ssl
      - ./.data/openresty/logs:/usr/local/openresty/nginx/logs
      # frontend
      - ./build_client:/frontend/client
    ports:
      - "80:80"
      - "443:443"

  client:
    <<: *common
    container_name: client
    command: /bin/sh -c "
      cd /frontend
      && mkdir -p build_client && cp -r static/i build_client
      && node_modules/.bin/webpack --color
      "
    volumes:
      # sources
      - ./:/frontend

  service-tests:
    <<: *common
    <<: *frontend-volumes
    container_name: $SERVICE_TESTS_HOST
    command: /bin/sh -c "cd /frontend && node_modules/.bin/ts-node-dev -P server/tests/tsconfig.json -r tsconfig-paths/register --no-notify --all-deps server/tests/server.ts"
    expose:
      - "$SERVICE_TESTS_PORT"

  service-layouts:
    <<: *common
    <<: *frontend-volumes
    container_name: $SERVICE_LAYOUTS_HOST
    command: /bin/sh -c "cd /frontend && node_modules/.bin/ts-node-dev -P server/layouts/tsconfig.json -r tsconfig-paths/register --no-notify --all-deps server/layouts/server.ts"
    expose:
      - "$SERVICE_LAYOUTS_PORT"

  database:
    <<: *common
    image: mongo
    container_name: database
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_PASSWORD
    ports:
      - "$DATABASE_PORT:27017"
    volumes:
      - ./.data/db:/data/db

networks:
  advanced-testing-network:
